-- MySQL Script generated by MySQL Workbench
-- Fri Jun 15 12:10:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ts_resume
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ts_resume` ;

-- -----------------------------------------------------
-- Schema ts_resume
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ts_resume` DEFAULT CHARACTER SET utf8 ;
USE `ts_resume` ;

-- -----------------------------------------------------
-- Table `ts_resume`.`user_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ts_resume`.`user_type` ;

CREATE TABLE IF NOT EXISTS `ts_resume`.`user_type` (
  `user_type_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_type_text` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_resume`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ts_resume`.`user` ;

CREATE TABLE IF NOT EXISTS `ts_resume`.`user` (
  `user_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL UNIQUE,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `last_login` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_date_time` DATETIME NOT NULL,
  `is_active` TINYINT(1) NULL DEFAULT 0,
  `user_type` ENUM('NEW', 'PREMIUM', 'STANDARD') NOT NULL DEFAULT 'NEW',
  `fk_user_type_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_user_type_idx` (`fk_user_type_id` ASC),
  CONSTRAINT `fk_user_user_type`
    FOREIGN KEY (`fk_user_type_id`)
    REFERENCES `ts_resume`.`user_type` (`user_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_resume`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ts_resume`.`address` ;

CREATE TABLE IF NOT EXISTS `ts_resume`.`address` (
  `address_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `state` VARCHAR(255) NULL,
  `postal_code` VARCHAR(45) NULL,
  `country` VARCHAR(255) NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_resume`.`resume`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ts_resume`.`resume` ;

CREATE TABLE IF NOT EXISTS `ts_resume`.`resume` (
  `resume_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT UNSIGNED NOT NULL,
  `resume_name` VARCHAR(255) NULL,
  `template_id` SMALLINT DEFAULT 1,
  `created_on_time` DATETIME NULL,
  `last_accessed_time` TIMESTAMP NULL,
  PRIMARY KEY (`resume_id`),
  INDEX `fk_resume_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_resume_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `ts_resume`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ts_resume`.`personal_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ts_resume`.`personal_info` ;

CREATE TABLE IF NOT EXISTS `ts_resume`.`personal_info` (
  `personal_info_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` SET('MR', 'MISS', 'MRS', 'DR') NULL,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `name_in_full` VARCHAR(255) NULL,
  `dob` DATE NULL,
  `email` VARCHAR(255) NOT NULL,
  `mobile` VARCHAR(20) NOT NULL,
  `profile_summary` TEXT NULL,
  `address_id` BIGINT UNSIGNED NOT NULL,
  `home_phone` VARCHAR(20) NULL,
  `resume_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`personal_info_id`),
  INDEX `fk_personal_info_address_idx` (`address_id` ASC),
  CONSTRAINT `fk_personal_info_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `ts_resume`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,  
  CONSTRAINT `fk_personal_info_resume`
    FOREIGN KEY (`resume_id`)
    REFERENCES `ts_resume`.`resume` (`resume_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)

ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_resume`.`experience`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ts_resume`.`experience` ;

CREATE TABLE IF NOT EXISTS `ts_resume`.`experience` (
  `experience_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(255) NULL,
  `position_held` VARCHAR(255) NULL,
  `from_year` SMALLINT NULL,
  `to_year` SMALLINT NULL,
  `from_month` TINYINT NULL,
  `to_month` TINYINT NULL,
  `description` TEXT NULL,
  `resume_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`experience_id`),
  INDEX `fk_experience_resume_idx` (`resume_id` ASC),
  CONSTRAINT `fk_experience_resume`
    FOREIGN KEY (`resume_id`)
    REFERENCES `ts_resume`.`resume` (`resume_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_resume`.`education`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ts_resume`.`education` ;

CREATE TABLE IF NOT EXISTS `ts_resume`.`education` (
  `education_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `school` VARCHAR(255) NOT NULL,
  `degree` VARCHAR(255) NULL,
  `field_of_study` VARCHAR(255) NULL,
  `from_year` SMALLINT NULL,
  `to_year` SMALLINT NULL,
  `from_month` TINYINT NULL,
  `to_month` TINYINT NULL,
  `description` TEXT NULL,
  `resume_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`education_id`),
  INDEX `fk_education_resume_idx` (`resume_id` ASC),
  CONSTRAINT `fk_education_resume`
    FOREIGN KEY (`resume_id`)
    REFERENCES `ts_resume`.`resume` (`resume_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_resume`.`skill_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ts_resume`.`skill_category` ;

CREATE TABLE IF NOT EXISTS `ts_resume`.`skill_category` (
  `skill_category_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `skill_category_text` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`skill_category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_resume`.`skill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ts_resume`.`skill` ;

CREATE TABLE IF NOT EXISTS `ts_resume`.`skill` (
  `skill_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `skill_name` VARCHAR(255) NULL,
  `skill_category_id` INT UNSIGNED NOT NULL,
  `skill_level_id` TINYINT NULL,
  `description` TEXT NULL,
  `resume_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`skill_id`),
  INDEX `fk_skill_skill_category_idx` (`skill_category_id` ASC),
  INDEX `fk_skill_resume_idx` (`resume_id` ASC),
  CONSTRAINT `fk_skill_skill_category`
    FOREIGN KEY (`skill_category_id`)
    REFERENCES `ts_resume`.`skill_category` (`skill_category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_skill_resume`
    FOREIGN KEY (`resume_id`)
    REFERENCES `ts_resume`.`resume` (`resume_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ts_resume`.`certificate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ts_resume`.`certificate` ;

CREATE TABLE IF NOT EXISTS `ts_resume`.`certificate` (
  `certificate_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `authority` VARCHAR(255) NULL,
  `code_url` VARCHAR(255) NULL,
   `date_issued` DATE NULL,
  `description` TEXT NULL,
  `resume_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`certificate_id`),
  INDEX `fk_certificate_resume_idx` (`resume_id` ASC),
  CONSTRAINT `fk_certificate_resume`
    FOREIGN KEY (`resume_id`)
    REFERENCES `ts_resume`.`resume` (`resume_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
